os:
  - linux
  - osx

before_install:
  - if [ "TRAVIS_OS_NAME" = "osx" ];   then brew update            ; fi
  - if [ "TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
