name: CI

on: [push]

jobs:
  test:
    name: Test dotfiles install without error
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set linux environment variable
        if: matrix.os == 'ubuntu-latest'
        run: export TRAVIS_OS_NAME=linux
      - name: Set macOS environment variable
        if: matrix.os == 'macOS-latest'
        run: export TRAVIS_OS_NAME=osx
      - name: Set windows environment variable
        if: matrix.os == 'windows-latest'
        run: export TRAVIS_OS_NAME=windows

      - name: Install
        run: ./.travis/install.sh

      - name: Script
        run: ./.travis/script.sh

